<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-S944CTM" ignored="2" name="Default test(failed)" tests="1" failures="1" timestamp="20 Jul 2019 17:34:31 GMT" time="0.062" errors="0">
  <testcase name="test3" time="0.015" classname="demo.testngretryfaileddemo">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at demo.testngretryfaileddemo.test3(testngretryfaileddemo.java:23)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.0" classname="demo.testngretryfaileddemo">
    <ignored/>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="demo.testngretryfaileddemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
